# Generated by Django 3.0.5 on 2020-05-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('cl', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
            ],
        ),
    ]
